### PR TITLE
Improve declarative language configuration

### PR DESCRIPTION
**Pull request by crbelaus**
As explained in [the documentation][1] VSCode supports declarative configuration for language features. This MR aims to improve the current language configuration both for Elixir source code and for EEx templates.

The included improvements are:
- For Elixir source code
  - [x] Rename `elixir.configuration.json` to `elixir-language-configuration.json`. Files whose name ends with `language-configuration.json` get [auto-completion and validation in VScode][2].
  - [x] Avoid autoclosing quotes in strings and comments.
  - [x] Use declarative configuration for indentation patterns. There is no more need for the programmatic configuration in `configuration.ts` file.
  - [x] Autoclose `<<` with their corresponding `>>` for ease when defining binaries.
- For EEx templates
  - [x] Add declarative configuration file `html-eex-language-configuration.json` that:
  - [x] Enables easy line or block comment with the corresponding VSCode shortcuts.
  - [x] Automatically close `<%` tags for embedding Elixir code with the corresponding `%>`.

This PR should fix issues #87 and #51.

[1]: https://code.visualstudio.com/api/language-extensions/overview#declarative-language-features
[2]: https://code.visualstudio.com/api/language-extensions/language-configuration-guide

### CODE REVIEW

**Comment by crbelaus** [comment]
This PR should also fix issue #87. When using the `ctrl+/` shortcut in EEx templates, the selected line or lines will be surrounded by `<%# ... %>` tags.

**Comment by jayjun** [comment]
@crbelaus Great pull request! Just a suggestion, I would take this opportunity to correct any “Eex”  to “EEx” too. See #84.

**Comment by crbelaus** [comment]
Thank you very much @jayjun !!

I've thought about changing "Eex" to "EEx" in the language names. At the end I've decided to keep it out of this pull request since this may break end-users configurations. For example, if a user has this configuration:

```json
// Enable emmet in Elixir templates
"emmet.includeLanguages": {
        "HTML (Eex)": "html",
}
```

It would stop working and the user should change it to:

```json
"emmet.includeLanguages": {
        "HTML (EEx)": "html",
}
```

I don't really know how @JakeBecker would like to handle this. Maybe we could put a warning in the README, or leave both configurations working for a certain time and then deprecate the old one. There are multiple options, and I would prefer them to be clear until changing anything related.

**Comment by crbelaus** [comment]
I've updated this PR with an autoclosing improvement in EEx tags and with new autoclosing for binary definitions in Elixir files.

**Comment by fkumro** [comment]
Would love to see this merged and released ! Nice work @crbelaus 👍

**Comment by crbelaus** [comment]
Reviewing the code of my PR I am now having doubts about whether the snippets configuration is necessary, since they are [already provided by the Language Server][1].

[1]: https://github.com/JakeBecker/elixir-ls/blob/f297d32aa622748d40721a1bc3c5c5f9e2513c66/apps/language_server/lib/language_server/providers/completion.ex#L16

**Comment by crbelaus** [comment]
I've been running it daily in my development machine without problems and I've finally decided to remove the snippets to avoid duplicating functionality already provided by the language server.

@JakeBecker I think that this PR is finally ready to review. I've also updated the PR description to remove all references to snippets.

**Comment by JakeBecker** [comment]
This is wonderful, thank you so much!

**Pull request merged**
