### PR TITLE
Add missing comma in the closing pairs list

### PR DESCRIPTION
**Pull request by IvanIvanoff**

### CODE REVIEW

**Comment by shouya** [comment]
Hi @JakeBecker, could you please merge this pull request? It's cause a trouble with https://github.com/CoenraadS/Bracket-Pair-Colorizer-2.

**Comment by ianatha** [comment]
I encountered this too.

**Comment by IvanIvanoff** [comment]
ping @JakeBecker

**Comment by ihumanable** [comment]
I've encountered this as well, you can edit the file locally to get the plugin working again, but it's definitely a bad user experience

**Comment by axelson** [comment]
If you're running into this you may be interested in the elixir-ls fork which has fixed this issue. The vscode plugin repository is at https://github.com/elixir-lsp/vscode-elixir-ls/ and it is available on the VisualStudio marketplace: https://marketplace.visualstudio.com/items?itemName=elixir-lsp.elixir-ls

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

If you're still interested in merging this PR, please do the following:

1. Check that the issue you're addressing still occurs with the latest version of the VS Code plugin (which is published from the new repo)
2. If your PR references a Github issue, check if there's already an issue filed on the new repo and create one if not
3. Rebase your PR from the new repo (which has diverged significantly) and re-submit it there.

Thank you!

**Pull request closed without merging**
