### PR TITLE
Support Phoenix LiveView

### PR DESCRIPTION
**Pull request by leandrocp**
Create a new config based on existing EEx and HTML (EEx) to support `.html.leex` and `.leex` files.

See https://github.com/JakeBecker/elixir-ls/pull/163

### CODE REVIEW

**Comment by leandrocp** [comment]
@JakeBecker or @OvermindDL1 can you take a look ? It's not recognizing `.html.leex` files as HTML (Leex). Instead, it's resolving it as Plain text, but I don't know what's missing.

**Comment by OvermindDL1** [comment]
I don't really know vscode well, I more use emacs and atom due to features still lacking in vscode and its plugins...  ^.^;

**Comment by leandrocp** [comment]
Updated with master:

Screen Shot 2019-05-24 at 11 53 08

On the left you can see #129 and on the right is the support for `.leex` and `.html.leex` files (added on this PR)

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

If you're still interested in merging this PR, please do the following:

1. Check that the issue you're addressing still occurs with the latest version of the VS Code plugin (which is published from the new repo)
2. If your PR references a Github issue, check if there's already an issue filed on the new repo and create one if not
3. Rebase your PR from the new repo (which has diverged significantly) and re-submit it there.

Thank you!

**Pull request closed without merging**
